### ISSUE TITLE
docs: 📚 add new Synergy branding to Storybook and GitHub and everywhere

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#150]
# Description

Every place where we communicate Synergy outside, we should present the new logo, e. g. as favicon, logo etc.

# Rationale

We want to make our brand Synergy stronger. :)

# DoD

- [x] Create Artboards with safe space around the logo to export them appropriately
- [x] Find a place in Figma where the logo is maintained (maybe the Helper Library?)
- [x] Export svg, png of logo + icon into #internal repo
- [x] Github icon
- [x] Storybook icon
- [x] Figma workspace / project icon
- [x] Figma file cover template
- [x] Intranet pages
- [x] Comm Channels

**Comment by eileenwegner** [comment]
**Favicon**
![Image](https://github.com/SickDesignSystem/synergy/assets/148873173/84cdd52a-5902-4538-b8a1-a13318958057)


**Profile Picture**
![Image](https://github.com/SickDesignSystem/synergy/assets/148873173/33a426a0-4aec-4107-9c72-68c90c77c51f)

**Comment by reichst1SICKAG** [comment]
Thanks @eileenwegner 
I'll export some versions into #internal to have a 'stable' released version there to use, download or reference.
