### ISSUE TITLE
chore: 🔧 Remove co-dependency between vendorism and build tasks

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#156]
# Description

The problem is that build scripts and vendorism currently share the configuration for created events and components, which will make it impossible to export components not created via vendorism.

# Rationale

Builds and Vendorism currently share too many dependencies (e.g. the exported components), which will make it impossible to add custom components in the future.

# DoD

- [x] Use vendorism as a standalone tool to just get components and events from shoelace.
- [x] Create `synergy.ts` and all wrappers from `packages/components/src/components` dynamically. This also means all components flagged as dependencies will be part of the bundles.
- [x] Newly created components **not** included via vendorism must be part of exports and wrappers automatically.
- [x] Newly created components included via vendorism must still be part of exports and wrappers automatically.
- [x] Always export all components in angular/react.

See original conversation at https://github.com/SickDesignSystem/synergy/pull/154#issuecomment-1815819642 for reference. Rough outline at https://github.com/SickDesignSystem/synergy/pull/154#issuecomment-1815862518.

**Comment by mariohamann** [comment]
@schilchSICKAG Do we need some further information regarding events?

**Comment by mariohamann** [comment]
Yah, that's why I'm unsure – what happens if we create own events? Do we then have the same problem?

**Comment by schilchSICKAG** [comment]
> Yah, that's why I'm unsure – what happens if we create own events? Do we then have the same problem as for the exported components?

You are right, we would eventually try to mirror shoelaces settings for this, so we would also have to include it from the filesystem, right? This makes it a bit harder. Mind if we tackle the pressing bits first? My impression is that this is quite hard to do and will not move the MVP further, as we currently are only providing Shoelace-Custom-Components.

Would create another issue for this when this issue here is resolved if you are ok with that.

**Comment by schilchSICKAG** [comment]
> > Yah, that's why I'm unsure – what happens if we create own events? Do we then have the same problem as for the exported components?
> 
> You are right, we would eventually try to mirror shoelaces settings for this, so we would also have to include it from the filesystem, right? This makes it a bit harder. Mind if we tackle the pressing bits first? My impression is that this is quite hard to do and will not move the MVP further, as we currently are only providing Shoelace-Custom-Components.
> 
> Would create another issue for this when this issue here is resolved if you are ok with that.

I just checked, fortunately it is already built in an way that uses the filesystem for events, so they will automatically get picked up via a `*` export.
