### ISSUE TITLE
chore: 🔧 "register" changes in `components` when there were only changes in `angular`/`react`

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#182]
# Description

> Currently the React and Angular wrapper versions are bound to the components package. This means that a bug-fix in the wrappers layer cannot be deployed without doing a change in the components package.
> On the other hand this version coupling is needed, so there is no misunderstanding which wrapper version fits to which components version.

# Rationale

As a maintainer of the Synergy Design System, I want to be able to make changes in the Angular/React packages (e. g. changes in package.json or README etc.) which should lead to updates of the components package WITHOUT doing fake commits in the components packge.

More context: https://github.com/SickDesignSystem/Internal/discussions/48

**Comment by mariohamann** [comment]
@klaarseSICKAG From my perspective everything is clear what the aim of the ticket is. Please have a look if something's missing. Would start with that tomorrow.

**Comment by klaarseSICKAG** [comment]
Agreed to the aim. I am very curious about the solution idea...

**Comment by mariohamann** [comment]
Here is the idea and solution: https://github.com/SickDesignSystem/synergy/pull/194 :)
