### ISSUE TITLE
feat: ✨ syn-icon

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#19]
**Description**:

As a user, I want to be able to use icons in my applications.

Applications:
- CMS / Website
- Embedded devices
- On premise
- digital services

Therefore we need easy and performant ways to include complete icon libraries and individual icons. They also have to be customizable in regards to coloring and overriding the icon library (brandability).

System icons (directly used in our own components) need to be bundled and still be overridable (e.g. chevron in accordion).

> [!Important]
> We need to investigate, how accessibility works with web fonts! For more information have a look at the [font awesome docu](https://fontawesome.com/docs/web/dig-deeper/accessibility#making-icons-accessible-manually) and this [accessible icons docu](https://stevenmouret.github.io/web-accessibility-guidelines/techniques/accessible-icons.html)

>[!Note]
> For now we will put the icons on hold and and leave them as they are. We got a first working draft for them (so they can be used in form elements like buttons etc.), but they are more complex and need more time to investigate.
>

**DoD**:

- [ ] Decide which pattern to use (see below)
- [ ] Create the component
- [ ] Create documentation
  - [ ] example for asset bundling
- [ ] Create stories
- [ ] Create tests

**Rationale**:

The need for displaying one to many icons may arise in various places of an application. Also, multiple components may want to display icons as part of their layout (e.g. the Caret Sign used in most drop-downs to indicate it is open or closed).

Do we need to include following icons: https://brand.sick.com/document/14/ ?

**Features**:

The component should provide an easy way to display a given glyph from a icon font. Currently, we plan to support `Material Icon`. It must be discussed if we want to either __use the slotted content__ or __a prop__ as source of the glyph.

**Example**:

```html
<!--
Usage with a slot.
Note we will also have to make sure to strip any white space, otherwise example B will not work
-->

<!-- Example A: Use "action/save" as the glyph -->
<sds-icon>action/save</sds-icon>

<!-- Example B: Use "action/save" as the glyph. We have to make sure to strip white space! -->
<sds-icon>
  action/save
</sds-icon>

<!-- Example C: Use a prop named "glyph" -->
<sds-icon glyph="action/save"></sds-icon>
```

**Comment by kirchsuSICKAG** [comment]
Further input for the creation of the icon:

there are applications, that can not use assets. They only can have one big file for the whole application. Therefore we need the possibility to make the icons available with javascript.
Possible way to achieve this with the shoelace icons:

- write a generator which automatically creates an object from the svg´s of the item library. Result will look something like this

`
{
  'chevron-down': "<svg>...</svg>",
  'chevron-left': "<svg>...</svg>",
}
` 
- make the result available in the icon library
- the result can be used by others via overriding the resolve function of shoelace icon. For an example see how shoelace handles its system icon (https://github.com/shoelace-style/shoelace/blob/next/src/components/icon/library.system.ts [shoelace doc](https://shoelace.style/components/icon#customizing-the-default-library) )
