### ISSUE TITLE
feat: ✨ Add support for Chromatic into Storybook

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#21]
## User Story

As a Synergy maintainer I want to get feedback on Visual Regressions when creating a PR. The PR should be blocked, as long as changes in Chromatic aren't accepted. When the PR is merged, the changes should be automatically the new baseline.

### Organizational
- [x] One person from SICK creates a new chromatic account or connects to an existing one
- [x] Check if every team member can log in into Chromatic with their GitHub account and should be able to see the project
- [x] All (SICK) administrators in the projects are defined on Chromatic

### Code
- [x] Add Chromatic as dependency
- [x] Make appropriate builds and direct Chromatic to the right folder
- [x] Add CI/CD support via github-actions for automatic PR checks (see https://github.com/solid-design-system/solid/blob/main/.github/workflows/chromatic-pr.yml for reference)
- [x] Add CI/CD support via github-actions for updating the baseline when merging into main (see https://github.com/solid-design-system/solid/blob/main/.github/workflows/chromatic-main.yml for reference)

**Rationale**:

This feature is needed for a seamless Workflow between design and development.

**Comment by schilchSICKAG** [comment]
Chromatic-Account at https://www.chromatic.com/settings?accountId=64f819d70a69cb8728e06dae, will already sync with Github Account settings

**Comment by mariohamann** [comment]
@Gwenevere Could you have a look at that after the other ticket? :)

**Comment by mariohamann** [comment]
Done.
