### ISSUE TITLE
feat: ✨ Automatically generate a components manifest for components

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#25]
**Description**:

As a developer, I want to have a machine readable representation of all components in the library.

**Rationale**:

This feature will make it possible to provide tooling around the created web-components, e.g. for creating auto-completion helpers, provide utilities that create framework wrappers or make the components useable in other third party systems.

**Comment by klaarseSICKAG** [comment]
Needed for:
- Automatically generated StoryBook story
- Angular Wrapper
- UIBuilder

Expected outcome:
- list of differences between CEM and components.json
- have a cli ready for generating the CEM
