### ISSUE TITLE
feat: ✨ Add support for automatic deployments

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#26]
**Description**:

As a developer for Synergy I want to create a new version of all packages and publish them on NPM as soon as we merge on relevant branch (e. g. `main` or `alpha`).

**Action Items**:

- [x] Install `pnpm i -D @semantic-release/changelog @semantic-release/git semantic-release semantic-release-monorepo` in every releasable package (`packages/(components/assets/tokens)`)
- [x]  Setup the release config as done here: https://github.com/solid-design-system/solid/blob/46135c5a21ec5724c700988c73bb4f22e497b4be/packages/tokens/package.json#L37 – just adapt `releases.branches` to the following: `['+([0-9])?(.{+([0-9]),x}).x', 'main', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}]`
- [x] Make everything in a `alpha` branch, so that we can do `alpha` releases: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
- [x] Setup a `release.yml` as done here: https://github.com/solid-design-system/solid/blob/main/.github/workflows/release.yml (ask @schilchSICKAG or @kirchsuSICKAG NPM_TOKEN and GH_Token we should use)
- [x] Try to run `semantic-release -d` in every package and try to fix stuff accordingly. :)

**Comment by klaarseSICKAG** [comment]
blocked by https://github.com/SickDesignSystem/Internal/issues/2

**Comment by mariohamann** [comment]
Done.
