### ISSUE TITLE
feat: ✨ Add package to support automated tests

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#34]
**Description**:

As a developer, I want to have the ability to validate my changes by using automated tests. We have chosen [playwright](https://playwright.dev/) as our framework of choice. This issue handles the following tasks:

- [ ] Creation of the new internal test package.
- [ ] Configuration of playwright.
- [ ] Installation of axe plugin.

**Rationale**:

Without this feature we will not be able to validate our work.

**Comment by klaarseSICKAG** [comment]
do we really need a separate package?

**Comment by schilchSICKAG** [comment]
Already done in #48. We are using shoelaces tests initially
