### ISSUE TITLE
docs: 📚 Autocompletion in HTML

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#44]
---

**Description**:

As a user, I want to be able to get vscode autocompletion for the components

**Rationale**:

Better DX

**Comment by schilchSICKAG** [comment]
See the following for implementation details:

- ✔ Already done for the internal project at https://github.com/SickDesignSystem/synergy/blob/chore/setup-vendored-unified-architecture/.vscode/settings.json#L72
- https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md
- https://code.visualstudio.com/Docs/languages/html#_html-custom-data
- https://github.com/microsoft/vscode-custom-data

**Comment by klaarseSICKAG** [comment]
add documenation how to load the vscode file in the README
