### ISSUE TITLE
feat: ✨ Angular component support

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#45]
Description:

As a user, I want to be able to use the components in Angular with correct intelli-sense, event and attribute handling.

Rationale:

Better DX

**Comment by klaarseSICKAG** [comment]
refers to https://github.com/angular/angular/issues/50226

**Comment by schilchSICKAG** [comment]
Also https://manuel-rauber.com/2021/02/23/youre-using-custom_elements_schema-wrong/

**Comment by schilchSICKAG** [comment]
Unfortunately, this will not be possible to be merged. We are using the `compnoents.json` for generating the wrappers, whereas Lit will use static code analysis to create the wrappers in the future. This means our code is largely incompatible with the thing that lit does.

For the future however, this is the reason I have opted to put `packages/react` and `packages/angular` under source control: When the lit cli becomes available, we will be able to remove our own build steps and components and use the official ones. This will make it possible to go forward with official sources. However, this is far from completed on lits side, so we have to check back again there after some time.
