### ISSUE TITLE
feat: ✨ Version information (debug)

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#49]
---

**Description**:

As a dev, I want to be able to check the version of the used elements in order to pinpoint the problem.

**Rationale**:
If there is an application problem we sometimes just get a link to the application from a non-dev with no version info. It would be good to at least have the means via debugging terminal to get the affected version.

**Comment by schilchSICKAG** [comment]
That is pretty easy to to. Just get the first item from the dom that is a synergy component and ask the registry for its version field (defined at https://github.com/SickDesignSystem/synergy/blob/main/packages/components/src/internal/synergy-element.ts#L104):

```javascript
const libVersion = customElements.get('syn-button').version; // 1.0.0-main.8
```
