### ISSUE TITLE
feat: ✨ add `syn-input`

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#57]
**Description**

The `syn-input` is a form field used to input any kind of single-line text, which could string, number etc..

**DoD**

- [x] The component looks like in Figma and reflects all its states
- [x] User can input text
- [ ] use Form support, Slots, Events, Methods, Parts from Shoelace
- [ ] Tested: Playwright + Chromatic
- [ ] create a proper documentation which contains at least everything from the Shoelace component
- [ ] Text in the documentation can be synced 

We have to have in mind that we're doing a `vendor-first` approach. Maybe find ways to be updatable even in styles file.

We estimated this a bit higher, as this will be the first time where we have to jump into Figma to read the documentation and have to get a common feeling on that. :)

## Functional deviations from brand
see https://brand.sick.com/document/51#/text-field
- no auto suggest
- stepper will be implemented in another component

**Comment by mariohamann** [comment]
Blocked by https://github.com/SickDesignSystem/design/issues/2
