### ISSUE TITLE
chore: 🔧 setup vendored & unified architecture

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#60]
## User Story
As a maintainer of Synergy Design System we want to reduce internal dependencies and move the scripts into their fitting packages.

### Description
- [x] make `packages/tokens` work with new Figma tokens
- [ ] make `packages/tokens` able to generate JS and SCSS tokens (as before) @Gwenevere 
- [x] make `packages/assets` able to fetch assets from Figma
- [x] make `packages/components` able to vendor and whitelabel stuff from Shoelace
- [x] make `packages/components` cli commands for vendorism @Gwenevere 
- [x] make `packages/components` able to lock vendored files @Gwenevere 
- [x] make `packages/components` able to eject vendored files @Gwenevere 
- [x] make `packages/components` able to generate vendored Storybook examples inside `packages/docs`
- [x] make `packages/docs` work with components in `packages/components` 
- [x] make `packages/docs` that it autogenerates Storybook controls via `custom-elements-manifest.config.js` from `packages/components`
- [x] make `packages/components` `pnpm test` work (Playwright is currently not found) @schilchSICKAG
- [x] make linting work everywhere @kirchsuSICKAG 
- [ ] decide how to handle interlinking between packages if needed files or folders are not going to be exported in the end (e. g. `docs` need `custom-elements-manifest.config.js` or `src/*` which won't be part of the final package) @schilchSICKAG

**Comment by mariohamann** [comment]
@Gwenevere Could you please take over the following subtasks:

- [ ] make `packages/components` cli commands for vendorism
- [ ] make `packages/components` able to lock vendored files
- [ ] make `packages/components` able to eject vendored files

Here some background information:


---

## make `packages/components` cli commands for vendorism
We want to have three scripts in `packages/components/package.json`
```js
...
    "vendor": "node scripts/vendorism.js",
    "vendor.get": "node scripts/vendorism.js -g",
    "vendor.set": "node scripts/vendorism.js -s",
...
```
In `scripts/vendorism.js` we should use `import commandLineArgs from 'command-line-args';` (see e. g. `custom-elements-manifest.config.js`) which reflect `-g`, `-s` or none of them. 


I should do this (dummy code ahead):

```js

// Only if not setOnly
if(!`-s`){
  await setSource(config);
}

// Only if not getOnly
if(!`-g`){
  /**
   * Generate the storybook files for all relevant components after shoelace is available so that they can be vendored
   */
  await Promise.all(components.map(async (component) => {
    const inputFilePath = `./vendor/docs/pages/components/${component}.md`;
    const outputFilePath = `./vendor/src/components/${component}/${component}.stories.ts`;
    await generateStorybookFile(inputFilePath, outputFilePath, component, libraryPrefix);
  }));

  // Move all files from '../docs/src/components' to './src/temp'
  await execSync('mv ../docs/stories/components ./src/temp');

  await setTarget(config);

  // Move files back from './src/temp' to '../docs/src/components'
  await execSync('mv ./src/temp ../docs/stories/components');
}
```


##  "make `packages/components` work to lock vendored files
You can get all files which were vendored like this:

```
const target = await setTarget(config);
const removedFiles = target.removedFiles; 
const newFiles = target.newFiles;
```

The old ones should be removed and the new ones should be added to `.vscode/settings.json` in the following format. `'files.readonlyInclude': {'file/example': true, 'file/second-example': true}`

Mind that it should use the path from the root, so `pacakges/components` should be added as well.


Here's something where you can start working with:
```js
export async function updateVsCodeReadOnlyFiles(remove, add, settingsPath = '../../.vscode/settings.json') {
  try {
    // Default settings object
    let settings = {};

    // If settings.json exists, read and parse it
    if (fs.existsSync(settingsPath)) {
      const rawData = fs.readFileSync(settingsPath, 'utf8');
      settings = JSON.parse(rawData);
    }

    // Remove files from files.readonlyInclude
    for (const file of remove) {
      if (!settings['files.readonlyInclude'][file]) return;
      delete settings['files.readonlyInclude'][file];
    }

    const readonlyFiles = {};
    for (const file of add) {
      readonlyFiles[file] = true;
    }

    // Override files.readonlyInclude with the provided files object
    settings['files.readonlyInclude'] = { ...readonlyFiles, ...settings['files.readonlyInclude'] };

    // Write the updated settings back to settings.json
    await fs.mkdirSync(settingsPath.split('/').slice(0, -1).join('/'), { recursive: true });
    await fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 4), 'utf8');
  } catch (error) {
    console.error('An error occurred while updating settings:', error);
  }
}
```

##  "make `packages/components` work to eject vendored files


We want to have another script in `packages/components/package.json`
```js
...
    "vendor.eject": "node scripts/vendorism.js -e",
...
```

The command should get an argument, being the file path so people can do:

`pnpm vendor.eject src/components/input/input.style`.

It should use the eject function by vendorism to eject files + it should remove the file from `.vscode/settings.json`:

https://github.com/mariohamann/vendorism#eject

Dummy code ahead:

```js

// have that before the other scripts...
if('-e'){
  eject(arg);
  updateVsCodeReadOnlyFiles([arg]);
  return; // ...so we can break it here.
}
```

**Comment by schilchSICKAG** [comment]
> decide how to handle interlinking between packages if needed files or folders are not going to be exported in the end

Do you have more examples or are there just the issues with the docs package currently? I have also seen this as a blocker for `make-react` as it needs correct types for events (taken from the `events/events.ts` and other files).
