### ISSUE TITLE
feat: ✨ vendor `syn-input`

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#69]
**Description**

As a Synergy developer I have to be able make components conform to brand. The `syn-input` per default contains a `pill` and a `filled` attribute which isn't conform. We have to find a way to either remove them, document them properly or similar. 

Possibilities are:

1. Using a transform in `vendorism.js` to remove the lines
2. Just remove the CSS so it doesn't change anything
3. Edit custom-elements-manifest.json to document that it shouldn't it be used in SICK
4. Think about other ways

We have to have in mind that we're doing a `vendor-first` approach and to be updatable as much as possible without violating brand.

**DoD**

- [ ] make `filled` brand compliant
- [ ] make `pill` brand compliant
- [ ] Tested: Playwright + Chromatic

**Comment by mariohamann** [comment]
Relates to https://github.com/orgs/SickDesignSystem/projects/2/views/1?filterQuery=remove&pane=issue&itemId=41077052

**Comment by klaarseSICKAG** [comment]
blocked by #57
