### ISSUE TITLE
feat: ✨ syn-radio

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#76]
**Description**

The `syn-radio` consits of 4 different elements: the grouping elemente`syn-radio-group` and `syn-button-group` and the interactive elements`syn-radio` and `syn-radio-button`.

`syn-radio`s are a collection of elements which which can be toggled in a way that only one can be active or none as a starting state inside a `syn-radio-group`.

**DoD**

- [ ] The component looks like in Figma and reflects all its states
- [ ] User can toggle between components in one group
- [ ] use Form support, Slots, Events, Methods, Parts from Shoelace
- [ ] Tested: Playwright + Chromatic
- [ ] create a proper documentation which contains at least everything from the Shoelace component
- [ ] Text in the documentation can be synced 
- [ ] vendor syn-radio-button: delete pill attribute, button--default -> button--primary
- [ ] component is integrated into react and angular demos and verified

**Comment by reichst1SICKAG** [comment]
Name and types from Figma are:
syn-radio for the single element
syn-radio-group for multiple elements in a group

Is syn-radio-button more like a [button-group](https://shoelace.style/components/button-group)? Do we need both?

**Comment by klaarseSICKAG** [comment]
the button-group looks just like an element for visually grouping buttons. I don't think we currently need it.

**Comment by reichst1SICKAG** [comment]
I agree for the button-group.

I would also move the `syn-radio-button` into a new ticket, as we also don't cover this in design (yet)
