### ISSUE TITLE
chore: 🔧 Semantic-Release does not work in CI/CD

### ISSUE THREAD

**Issue by schilchSICKAG** [SickDesignSystem/synergy#81]
**Description**:

The current CI/CD setup does not work as there are missing jobs (e.g. `pnpm release` when trying to push releases on `main`. See https://github.com/SickDesignSystem/synergy/actions/runs/6573954694/job/17858012681.

We may also want to check if we can work with `pnpm publish` via `semantic-release` instead of releasing via `npm publish`. This would make it possible to also automatically build a dependency map.

**Rationale**:

We need the ability to automatically create releases with correct builds.

**Comment by mariohamann** [comment]
@Gwenevere Could you have a look at that? :)

**Comment by mariohamann** [comment]
Done.
