### ISSUE TITLE
feat: ✨add SCSS and JS support for tokens

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#93]
## Rationale

As a developer using the Synergy Design System I want to be able to use themable tokens in SCSS and JS.

## Description

The final result should look like this:

`dist/js/tokens.js`

```js
export const SynPrimaryColor500 = "var(--syn-primary-color-500)";
export const SynPrimaryColor600 = "var(--syn-primary-color-600)";
```

`dist/scss/_tokens.scss`

```scss
$synPrimaryColor500: var(--syn-primary-color-500);
$synPrimaryColor600: var(--syn-primary-color-600);
```

The final color will be resolved on runtime depending on the used theme `light.css` or `dark.css` or any custom theme for whitelabeling.

As working with Style Dictionary is pretty... painy... we highly suggest to to do following:

1. add a new node script in `packages/tokens/scripts` like `create-scss-and-js-tokens.js`
2. add it to the end of `build.js`
3. the script should run through every line of the generated `dist/css/light.css` and convert the property key according to the specification above

Hint: We should optimize the first line in the css that it doesn't look like this
```css
.syn-theme-light {  --syn-font-size-2x-small: 10px;
```

But like this:
```css
.syn-theme-light {
  --syn-font-size-2x-small: 10px;
```

On top I propose to rename the output folder of the themes from `dist/css/...` to `dist/themes/...`, as they are technically something different than what we do with `scss` and `js`. What do you think @schilchSICKAG ?

We should make sure that the stuff is correctly done when creating the npm package and that it is exported in the `package.json`

**Comment by schilchSICKAG** [comment]
Please make also sure to add the created javascript file to the package exports to it gets available when using `import * as tokens from '@synergy-design-system/tokens`
